version: '3.8'  # Specify the version of the compose file

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_CONF: |
        deprecated_features.permit.management_metrics_collection = true
    networks:
      - ap_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app_a:
    build: ./app_a
    container_name: app_a
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - ./app_a/access_points.json:/app/access_points.json
    networks:
      - ap_network

  app_b:
    build: ./app_b
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - ap_network
    deploy:
      replicas: 3

networks:
  ap_network:
    driver: bridge
